# Site settings
title: Jon Eisen
email: jon@joneisen.works
description: >
  The cogitation of a know-it-all code typist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joneisen.me" # the base hostname & protocol for your site
twitter_username: jm_eisen
github_username:  yanatan16

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Github Pages Supported Plugins
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
