# Site settings
title: Jon Eisen
email: jon@joneisen.me
description: >
  Data, running, code, running, homebrewing, running, etc
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://joneisen.me" # the base hostname & protocol for your site
github_username:  yanatan16

# Race Stuff
race_title: Races by Cowboy

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# Github Pages Supported Plugins
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
